apiVersion: v1
kind: Secret
metadata:
  name: mssql-db-secret
type: Opaque
data:
  PASSWORD: <base64-encoded-password>
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-db-secret
type: Opaque
data:
  USER: <base64-encoded-user>
  PASSWORD: <base64-encoded-password>
---
apiVersion: v1
kind: Secret
metadata:
  name: app-controller-secret
type: Opaque
data:
  Build__GithubPat: <base64-encoded-github-pat>
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
data:
  Admin__Email: <base64-encoded-email>
  Admin__Name: <base64-encoded-name>
  Admin__Password: <base64-encoded-password>
  Admin__Username: <base64-encoded-username>
  Jwt__Secret: <base64-encoded-secret>
---
apiVersion: v1
kind: Secret
metadata:
  name: recipe-search-secret
type: Opaque
data:
  AZURE_OPENAI_API_KEY: <base64-encoded-key>
  AZURE_OPENAI_BASE_URL: <base64-encoded-url>