apiVersion: v1
kind: Service
metadata:
  name: mssql-db
spec:
  selector:
    app: mssql-db
  ports:
    - name: "2603"
      port: 2603
      targetPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
spec:
  selector:
    app: postgres-db
  ports:
    - name: "2605"
      port: 2605
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: app-controller-api
spec:
  type: LoadBalancer
  selector:
    app: app-controller-api
  ports:
    - name: "2501"
      port: 2501
      targetPort: 8080
    - name: "2502"
      port: 2502
      targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: auth-api
spec:
  selector:
    app: auth-api
  ports:
    - name: "2503"
      port: 2503
      targetPort: 8080
    - name: "2504"
      port: 2504
      targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: recipe-search-api
spec:
  selector:
    app: recipe-search-api
  ports:
    - name: "2505"
      port: 2505
      targetPort: 2505